"""Every diagram in the documentation, as data.

One :class:`~render.Diagram` per picture. Coordinates are hand-placed on a
10-pixel grid, the same grid draw.io snaps to, so a box moved in the editor and
a box moved here land in the same places.

Keep a diagram to one idea. Where a picture would need a legend to be read, it
is two pictures.
"""

from render import Box, Diagram, Link

# --------------------------------------------------------------------------- #
# 1. Component layering
# --------------------------------------------------------------------------- #

ARCHITECTURE = Diagram(
    name="architecture",
    title="Component layering",
    caption="Who may import whom. Every arrow points down; there is no arrow back up.",
    boxes=(
        Box(
            id="g_app",
            label="app/  — the only layer that names an implementation",
            x=40,
            y=40,
            w=920,
            h=110,
            kind="group",
        ),
        Box(
            id="pages",
            label="Reflex app",
            sub="app/app.py, pages/",
            x=70,
            y=75,
            w=170,
            h=56,
            kind="app",
        ),
        Box(
            id="composition",
            label="composition.py",
            sub="builds every component",
            x=270,
            y=75,
            w=190,
            h=56,
            kind="app",
        ),
        Box(
            id="configuration",
            label="configuration.py",
            sub="AppConfig",
            x=490,
            y=75,
            w=170,
            h=56,
            kind="app",
        ),
        Box(
            id="workerproc",
            label="worker.py",
            sub="python -m app.worker",
            x=690,
            y=75,
            w=220,
            h=56,
            kind="app",
        ),
        Box(
            id="g_components",
            label="components/  — usable from a CLI, a worker or a test",
            x=40,
            y=200,
            w=920,
            h=230,
            kind="group",
        ),
        Box(
            id="ui",
            label="mailarc-ui",
            sub="the only one seeing Reflex",
            x=60,
            y=240,
            w=168,
            h=60,
            kind="ui",
        ),
        Box(
            id="sync",
            label="mailarc-sync",
            sub="engine · queue · worker",
            x=240,
            y=240,
            w=168,
            h=60,
            kind="sync",
        ),
        Box(
            id="analytics",
            label="mailarc-analytics",
            sub="derived nodes · vectors",
            x=420,
            y=240,
            w=168,
            h=60,
            kind="sync",
        ),
        Box(
            id="mcp",
            label="mailarc-mcp",
            sub="read-only tools · optional",
            x=600,
            y=240,
            w=168,
            h=60,
            kind="sync",
        ),
        Box(
            id="google",
            label="mailarc-google",
            sub="Gmail behind the port",
            x=780,
            y=240,
            w=168,
            h=60,
            kind="provider",
        ),
        Box(
            id="core",
            label="mailarc-core",
            sub="mail · archive · graph · database",
            x=310,
            y=350,
            w=440,
            h=60,
            kind="core",
        ),
        Box(
            id="g_stores",
            label="Stores",
            x=40,
            y=480,
            w=920,
            h=100,
            kind="group",
        ),
        Box(
            id="sqlite",
            label="SQLite",
            sub=".state/mail-archive.db",
            x=110,
            y=512,
            w=210,
            h=56,
            kind="store",
        ),
        Box(
            id="graphdb",
            label="Graph (FalkorDB)",
            sub="ground truth",
            x=380,
            y=512,
            w=210,
            h=56,
            kind="store",
        ),
        Box(
            id="blobs",
            label="Blob store",
            sub=".state/mailstore",
            x=650,
            y=512,
            w=210,
            h=56,
            kind="store",
        ),
        Box(
            id="rule",
            label="app/ may import any component. A component never imports app/.",
            sub="components/mailarc-core/tests/test_isolation.py fails if one does.",
            x=200,
            y=620,
            w=600,
            h=58,
            kind="note",
            bold=False,
        ),
    ),
    links=(
        Link(src="pages", dst="ui", exit="s", entry="n"),
        Link(src="composition", dst="sync", exit="s", entry="n"),
        Link(
            src="composition",
            dst="core",
            exit="w",
            entry="w",
            label="config + stores",
            # Below the top component row: the row grew a sixth box and moved
            # left, and at the old offset the label sat inside mailarc-sync.
            label_dy=88,
        ),
        Link(src="workerproc", dst="google", exit="s", entry="n"),
        Link(src="ui", dst="sync", exit="e", entry="w"),
        Link(src="ui", dst="core", exit="se", entry="nw"),
        Link(src="sync", dst="core", exit="s", entry="n"),
        Link(src="analytics", dst="core", exit="s", entry="n"),
        Link(src="mcp", dst="core", exit="s", entry="ne"),
        Link(src="google", dst="core", exit="s", entry="e"),
        Link(src="core", dst="sqlite", exit="sw", entry="n"),
        Link(src="core", dst="graphdb", exit="s", entry="n"),
        Link(src="core", dst="blobs", exit="se", entry="n"),
    ),
)

# --------------------------------------------------------------------------- #
# 2. The import pipeline
# --------------------------------------------------------------------------- #

PIPELINE = Diagram(
    name="import-pipeline",
    title="The import pipeline",
    caption=(
        "One page at a time, top to bottom. The queue is the backpressure, and "
        "behind it there is exactly one consumer."
    ),
    boxes=(
        Box(
            id="source",
            label="MailSourcePort",
            sub="Gmail · a folder of .eml files",
            x=320,
            y=40,
            w=250,
            h=58,
            kind="provider",
        ),
        Box(
            id="list",
            label="list_messages(cursor)",
            sub="one page of references",
            x=320,
            y=140,
            w=250,
            h=58,
            kind="sync",
        ),
        Box(
            id="filter",
            label="drop what this account already has",
            sub="one IN (…) per page",
            x=320,
            y=240,
            w=250,
            h=58,
            kind="sync",
        ),
        Box(
            id="fetch",
            label="fetch_raw(slice)",
            sub="semaphore · 8 streams · 5 retries",
            x=320,
            y=340,
            w=250,
            h=58,
            kind="sync",
        ),
        Box(
            id="parse",
            label="parse + store the bytes",
            sub="stdlib email, in a thread",
            x=320,
            y=440,
            w=250,
            h=58,
            kind="sync",
        ),
        Box(
            id="queue",
            label="asyncio.Queue",
            sub="a message, or a failure — never nothing",
            x=320,
            y=540,
            w=250,
            h=58,
            kind="accent",
        ),
        Box(
            id="consumer",
            label="the one archive consumer",
            sub="buffers up to batch_size",
            x=320,
            y=640,
            w=250,
            h=58,
            kind="accent",
        ),
        Box(
            id="graphwrite",
            label="1. MessageArchiver",
            sub="graph first, so a crash re-imports",
            x=320,
            y=740,
            w=250,
            h=58,
            kind="core",
        ),
        Box(
            id="ledger",
            label="2. record archived and failed",
            sub="one transaction per batch",
            x=320,
            y=840,
            w=250,
            h=58,
            kind="core",
        ),
        Box(
            id="checkpoint",
            label="3. checkpoint the cursor",
            sub="every checkpoint_every messages",
            x=320,
            y=940,
            w=250,
            h=58,
            kind="sync",
        ),
        Box(
            id="sqliteread",
            label="SQLite",
            sub="mail_archived_messages",
            x=660,
            y=240,
            w=210,
            h=58,
            kind="store",
        ),
        Box(
            id="blobstore",
            label="blob store",
            sub=".eml and attachments, by sha256",
            x=660,
            y=440,
            w=210,
            h=58,
            kind="store",
        ),
        Box(
            id="graphstore",
            label="graph",
            sub="nodes and edges",
            x=660,
            y=740,
            w=210,
            h=58,
            kind="store",
        ),
        Box(
            id="sqlitewrite",
            label="SQLite",
            sub="archived · failed · checkpoint",
            x=660,
            y=890,
            w=210,
            h=58,
            kind="store",
        ),
    ),
    links=(
        Link(src="source", dst="list", exit="s", entry="n"),
        Link(src="list", dst="filter", exit="s", entry="n"),
        Link(
            src="filter",
            dst="sqliteread",
            exit="e",
            entry="w",
            dashed=True,
            label="reads",
        ),
        Link(src="filter", dst="fetch", exit="s", entry="n"),
        Link(src="fetch", dst="parse", exit="s", entry="n"),
        Link(
            src="parse",
            dst="blobstore",
            exit="e",
            entry="w",
            dashed=True,
            label="writes",
        ),
        Link(src="parse", dst="queue", exit="s", entry="n"),
        Link(src="queue", dst="consumer", exit="s", entry="n"),
        Link(src="consumer", dst="graphwrite", exit="s", entry="n"),
        Link(src="graphwrite", dst="graphstore", exit="e", entry="w", dashed=True),
        Link(src="graphwrite", dst="ledger", exit="s", entry="n"),
        Link(src="ledger", dst="sqlitewrite", exit="e", entry="w", dashed=True),
        Link(src="ledger", dst="checkpoint", exit="s", entry="n"),
        Link(
            src="checkpoint",
            dst="list",
            exit="w",
            entry="w",
            label="while a next cursor comes back",
            stub=70,
        ),
    ),
)

# --------------------------------------------------------------------------- #
# 3. Graph ground truth
# --------------------------------------------------------------------------- #

GRAPH_MODEL = Diagram(
    name="graph-model",
    title="Graph ground truth",
    caption=(
        "Everything the provider actually sent. An analysis may add nodes beside "
        "these; it never edits them."
    ),
    boxes=(
        Box(
            id="message",
            label="Message",
            sub="id = canonical id",
            x=380,
            y=280,
            w=200,
            h=70,
            kind="core",
        ),
        Box(
            id="address",
            label="Address",
            sub="id = normalised address",
            x=380,
            y=40,
            w=200,
            h=62,
            kind="core",
        ),
        Box(
            id="thread",
            label="Thread",
            sub="id = account:thread",
            x=60,
            y=160,
            w=190,
            h=62,
            kind="core",
        ),
        Box(
            id="parent",
            label="Message",
            sub="the one replied to",
            x=60,
            y=280,
            w=190,
            h=62,
            kind="core",
        ),
        Box(
            id="label",
            label="Label",
            sub="id = account:name",
            x=60,
            y=400,
            w=190,
            h=62,
            kind="core",
        ),
        Box(
            id="attachment",
            label="Attachment",
            sub="id = sha256 of the file",
            x=700,
            y=280,
            w=200,
            h=62,
            kind="core",
        ),
        Box(
            id="account",
            label="Account",
            sub="id = SQLite row id",
            x=700,
            y=430,
            w=200,
            h=62,
            kind="core",
        ),
        Box(
            id="note",
            label="Properties on Message",
            sub=(
                "subject · subject_norm · sent_at · body_text · body_clean · "
                "simhash · participant_key · refs · eml_sha256 · embedding"
            ),
            x=280,
            y=560,
            w=560,
            h=62,
            kind="note",
            bold=False,
        ),
    ),
    links=(
        Link(src="message", dst="address", exit="nw", entry="sw", label="SENT_FROM"),
        Link(src="message", dst="address", exit="n", entry="s", label="SENT_TO"),
        Link(
            src="message",
            dst="address",
            exit="ne",
            entry="se",
            label="COPIED_TO / BLIND_COPIED_TO",
            label_dx=90,
        ),
        Link(src="message", dst="thread", exit="wn", entry="e", label="IN_THREAD"),
        Link(
            src="message",
            dst="parent",
            exit="w",
            entry="e",
            label="REPLIES_TO",
            label_dx=-14,
        ),
        Link(src="message", dst="label", exit="ws", entry="e", label="LABELED"),
        Link(
            src="message",
            dst="attachment",
            exit="e",
            entry="w",
            label="HAS_ATTACHMENT",
            label_dx=14,
        ),
        Link(
            src="message",
            dst="account",
            exit="es",
            entry="w",
            label="ARCHIVED_FROM",
        ),
        Link(src="message", dst="note", exit="s", entry="n", dashed=True, arrow=False),
    ),
)

# --------------------------------------------------------------------------- #
# 4. Job lifecycle
# --------------------------------------------------------------------------- #

JOB_LIFECYCLE = Diagram(
    name="job-lifecycle",
    title="Job lifecycle",
    caption=(
        "A compare-and-swap decides who claims a job; a lease decides how long "
        "they keep it."
    ),
    boxes=(
        Box(
            id="queued",
            label="queued",
            sub="waiting for a worker",
            x=60,
            y=180,
            w=180,
            h=62,
            kind="accent",
        ),
        Box(
            id="running",
            label="running",
            sub="worker_id + lease_until",
            x=360,
            y=180,
            w=200,
            h=62,
            kind="sync",
        ),
        Box(
            id="succeeded",
            label="succeeded",
            sub="",
            x=690,
            y=60,
            w=170,
            h=54,
            kind="sync",
        ),
        Box(
            id="failed",
            label="failed",
            sub="error is recorded",
            x=690,
            y=180,
            w=170,
            h=54,
            kind="store",
        ),
        Box(
            id="cancelled",
            label="cancelled",
            sub="asked to stop, not killed",
            x=690,
            y=300,
            w=170,
            h=54,
            kind="external",
        ),
        Box(
            id="enqueue",
            label="enqueue(kind, account)",
            sub="UI or scheduler",
            x=60,
            y=60,
            w=180,
            h=54,
            kind="ui",
        ),
        Box(
            id="heartbeat",
            label="heartbeat every 10 s",
            sub="pushes the lease out",
            x=360,
            y=60,
            w=200,
            h=54,
            kind="note",
            bold=False,
        ),
        Box(
            id="expiry",
            label="lease ran out",
            sub="reclaim_expired()",
            x=360,
            y=330,
            w=200,
            h=54,
            kind="note",
            bold=False,
        ),
    ),
    links=(
        Link(src="enqueue", dst="queued", exit="s", entry="n"),
        Link(src="queued", dst="running", exit="e", entry="w", label="claim()"),
        Link(src="heartbeat", dst="running", exit="s", entry="n", dashed=True),
        Link(src="running", dst="succeeded", exit="en", entry="w"),
        Link(src="running", dst="failed", exit="e", entry="w"),
        Link(
            src="running",
            dst="cancelled",
            exit="es",
            entry="w",
            label="cancel_requested",
        ),
        Link(src="running", dst="expiry", exit="s", entry="n", dashed=True),
        Link(
            src="expiry",
            dst="queued",
            exit="w",
            entry="s",
            label="back in the queue",
            label_dx=-40,
        ),
    ),
)

# --------------------------------------------------------------------------- #
# 5. Relational schema
# --------------------------------------------------------------------------- #

RELATIONAL = Diagram(
    name="relational-schema",
    title="What the relational store holds",
    caption=(
        "The graph holds what a message is. These six tables hold what we have "
        "done about it."
    ),
    boxes=(
        Box(
            id="accounts",
            label="mail_accounts",
            sub="provider · address · enabled · status",
            x=400,
            y=240,
            w=280,
            h=72,
            kind="core",
        ),
        Box(
            id="credentials",
            label="mail_credentials",
            sub="kind · secret (encrypted, opaque)",
            x=60,
            y=60,
            w=250,
            h=64,
            kind="store",
        ),
        Box(
            id="jobs",
            label="mail_sync_jobs",
            sub="kind · state · lease · counters",
            x=770,
            y=60,
            w=250,
            h=64,
            kind="sync",
        ),
        Box(
            id="checkpoints",
            label="mail_sync_checkpoints",
            sub="scope · cursor · messages_seen",
            x=60,
            y=430,
            w=250,
            h=64,
            kind="sync",
        ),
        Box(
            id="archived",
            label="mail_archived_messages",
            sub="provider id → canonical id",
            x=770,
            y=430,
            w=250,
            h=64,
            kind="accent",
        ),
        Box(
            id="failed",
            label="mail_failed_messages",
            sub="provider id · reason · detail",
            x=400,
            y=560,
            w=280,
            h=64,
            kind="external",
        ),
        Box(
            id="note",
            label="Rebuildable, not authoritative",
            sub=(
                "mail_archived_messages is a read model over the graph — the "
                "batch IN (…) the graph cannot answer cheaply."
            ),
            x=180,
            y=670,
            w=620,
            h=62,
            kind="note",
            bold=False,
        ),
    ),
    links=(
        Link(
            src="credentials", dst="accounts", exit="e", entry="wn", label="account_id"
        ),
        Link(src="jobs", dst="accounts", exit="w", entry="en", label="account_id"),
        Link(
            src="checkpoints", dst="accounts", exit="e", entry="ws", label="account_id"
        ),
        Link(src="archived", dst="accounts", exit="w", entry="es", label="account_id"),
        Link(src="failed", dst="accounts", exit="n", entry="s", label="account_id"),
        Link(src="archived", dst="note", exit="s", entry="e", dashed=True, arrow=False),
    ),
)

# --------------------------------------------------------------------------- #
# 6. Adding an account
# --------------------------------------------------------------------------- #

ACCOUNT_SETUP = Diagram(
    name="account-setup",
    title="Connecting a mailbox",
    caption="What happens between typing an address and having a mailbox that syncs.",
    boxes=(
        Box(
            id="form",
            label="1. Add the account",
            sub="fields come from the provider descriptor",
            x=40,
            y=40,
            w=250,
            h=64,
            kind="ui",
        ),
        Box(
            id="stored",
            label="2. Credential stored",
            sub="encrypted column, opaque blob",
            x=40,
            y=160,
            w=250,
            h=64,
            kind="store",
        ),
        Box(
            id="consent",
            label="3. Connect",
            sub="verify() — for Gmail, consent",
            x=40,
            y=280,
            w=250,
            h=64,
            kind="ui",
        ),
        Box(
            id="browser",
            label="Your browser",
            sub="Google's own consent screen",
            x=360,
            y=280,
            w=230,
            h=64,
            kind="external",
        ),
        Box(
            id="loopback",
            label="127.0.0.1:<free port>",
            sub="one-shot redirect listener",
            x=660,
            y=280,
            w=230,
            h=64,
            kind="external",
        ),
        Box(
            id="refresh",
            label="4. Refresh token saved",
            sub="back into mail_credentials",
            x=660,
            y=160,
            w=230,
            h=64,
            kind="store",
        ),
        Box(
            id="identity",
            label="5. Identity confirmed",
            sub="whose mailbox this really is",
            x=660,
            y=40,
            w=230,
            h=64,
            kind="core",
        ),
        Box(
            id="ready",
            label="6. Ready to import",
            sub="status: idle",
            x=360,
            y=40,
            w=230,
            h=64,
            kind="sync",
        ),
    ),
    links=(
        Link(src="form", dst="stored", exit="s", entry="n"),
        Link(src="stored", dst="consent", exit="s", entry="n"),
        Link(src="consent", dst="browser", exit="e", entry="w"),
        Link(src="browser", dst="loopback", exit="e", entry="w", label="code"),
        Link(src="loopback", dst="refresh", exit="n", entry="s"),
        Link(src="refresh", dst="identity", exit="n", entry="s"),
        Link(src="identity", dst="ready", exit="w", entry="e"),
    ),
)

# --------------------------------------------------------------------------- #
# 7. Deployment
# --------------------------------------------------------------------------- #

DEPLOYMENT = Diagram(
    name="deployment",
    title="Two ways to run it",
    caption=(
        "The same processes either way. What changes is who starts them and "
        "where the graph lives."
    ),
    boxes=(
        Box(
            id="g_desktop",
            label="macOS desktop — PROFILES=prod",
            x=40,
            y=40,
            w=430,
            h=420,
            kind="group",
        ),
        Box(
            id="tauri",
            label="Tauri shell",
            sub="mail-archive.app",
            x=80,
            y=90,
            w=350,
            h=54,
            kind="app",
        ),
        Box(
            id="dweb",
            label="Reflex app",
            sub="single port 8080",
            x=80,
            y=180,
            w=160,
            h=60,
            kind="app",
        ),
        Box(
            id="dworker",
            label="worker",
            sub="child process",
            x=290,
            y=180,
            w=140,
            h=60,
            kind="sync",
        ),
        Box(
            id="dfalkor",
            label="vendored FalkorDB",
            sub="redis-server + falkordb.so",
            x=80,
            y=280,
            w=350,
            h=54,
            kind="store",
        ),
        Box(
            id="dstate",
            label=".state/",
            sub="SQLite · blobs · graph data",
            x=80,
            y=370,
            w=350,
            h=54,
            kind="store",
        ),
        Box(
            id="g_server",
            label="Server — PROFILES=prod, APP__GRAPH__MODE=remote",
            x=530,
            y=40,
            w=430,
            h=420,
            kind="group",
        ),
        Box(
            id="g_procs",
            label="two units, one database",
            x=560,
            y=100,
            w=370,
            h=110,
            kind="group",
        ),
        Box(
            id="sweb",
            label="Reflex app",
            sub="supervise_worker: false",
            x=585,
            y=132,
            w=165,
            h=60,
            kind="app",
        ),
        Box(
            id="sworker",
            label="worker",
            sub="its own unit",
            x=775,
            y=132,
            w=135,
            h=60,
            kind="sync",
        ),
        Box(
            id="svolume",
            label="shared volume",
            sub="SQLite · blob store",
            x=560,
            y=300,
            w=170,
            h=80,
            kind="store",
        ),
        Box(
            id="sgraph",
            label="remote graph",
            sub="FalkorDB · Neo4j · Memgraph · AGE",
            x=750,
            y=300,
            w=190,
            h=80,
            kind="store",
        ),
    ),
    links=(
        Link(src="tauri", dst="dweb", exit="sw", entry="n"),
        Link(src="tauri", dst="dworker", exit="se", entry="n", dashed=True),
        Link(src="dweb", dst="dworker", exit="e", entry="w", label="starts"),
        Link(src="dweb", dst="dfalkor", exit="s", entry="nw"),
        Link(src="dworker", dst="dfalkor", exit="s", entry="ne"),
        Link(src="dfalkor", dst="dstate", exit="s", entry="n"),
        Link(src="g_procs", dst="svolume", exit="sw", entry="n"),
        Link(src="g_procs", dst="sgraph", exit="se", entry="n"),
    ),
)


ALL: tuple[Diagram, ...] = (
    ARCHITECTURE,
    PIPELINE,
    GRAPH_MODEL,
    JOB_LIFECYCLE,
    RELATIONAL,
    ACCOUNT_SETUP,
    DEPLOYMENT,
)
