services:
  app:
    container_name: mail-archive-dev
    image: mail-archive/ui-dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.13-bookworm
    volumes:
      - ../..:/workspaces:rw,cached
    command: sleep infinity
