profile: devcontainer

reflex:
  deploy_url: http://localhost
  frontend_port: 8080
  backend_port: 3030
  workers: 1

app:
  environment: container
  logging: logging.yaml

  database:
    echo: True
